DROP TABLE IF EXISTS TBL_PRODUCT;

CREATE TABLE TBL_PRODUCT (
  ITEM_NO NUMBER AUTO_INCREMENT  PRIMARY KEY,
  NAME VARCHAR(250) NOT NULL,
  AMOUNT NUMBER NOT NULL,
  INVENTORY_CODE LONG DEFAULT NULL
);